#' Create a Name Label Plot
#'
#' Generates a simple ggplot containing a centered text label, optionally
#' displayed inside a decorative box created with [plot_box()].
#'
#' @param name Character string to display in the plot.
#' @param name_size Numeric value controlling the size of the displayed text.
#'   Defaults to `15`.
#' @param name_color Character string specifying the text color. Can be any
#'   valid color understood by ggplot2 (e.g., hexadecimal color codes or named
#'   colors). Defaults to `"#235347"`.
#' @param name_font Character string specifying the font family for the text.
#' @param add_box Logical indicating whether to place the name inside a box
#'   generated by [plot_box()]. Defaults to `TRUE`.
#' @param ... Additional arguments passed to [plot_box()] when
#'   `add_box = TRUE`.
#'
#' @return
#' A `ggplot` object. When `add_box = TRUE`, the returned plot combines the
#' text label with the output of [plot_box()] using
#' [patchwork::inset_element()].
#'
#' @examples
#' plot_name("John Doe")
#'
#' plot_name(
#'   name = "Jane Smith",
#'   name_size = 12,
#'   name_color = "steelblue"
#' )
#'
#' @seealso
#' [plot_box()], [patchwork::inset_element()]
#'
#' @export

plot_name <- function(name,
                      name_size = 15,
                      name_color = "#235347",
                      name_font = NULL,
                      add_box = TRUE,
                      ...){

  p.name <- ggplot2::ggplot() +
    ggplot2::geom_text(
                       ggplot2::aes(x = 0.5, y = 0.5, label = name),
                       size = name_size, color = name_color,
                       family   = name_font,
                       fontface = "bold") +
    ggplot2::xlim(0, 1) +
    ggplot2::ylim(0, 1) +
    ggplot2::theme_void() +
    ggplot2::theme(
      plot.margin = ggplot2::margin(
        t = 1, r = 1, b = 1, l = 1 # around name/text itself hardly no margin
      )
    )

  if(add_box){

    p.box <- plot_box(...)

    p.name <- p.box +  # put p.name exactly in the middle of the box
      patchwork::inset_element(p.name, left = 0.04, bottom = 0, right = 0.96, top = 1)

  }

  return(p.name)

}
